### ISSUE TITLE
localtest with vagrant up failes. Too many files

### ISSUE THREAD

**Issue by TAlonglong** [metno/S-ENDA-csw-catalog-service#31]
The vagrant up fails with:
```
    localtest: Processing 33036 files
    localtest: Traceback (most recent call last):
    localtest:   File "/usr/local/bin/xmlconverter.py", line 75, in main
    localtest:     translate_and_write(xml_file=i, xslt=xslt, outdir=outdir)
    localtest:   File "/usr/local/bin/xmlconverter.py", line 50, in translate_and_write
    localtest:     xml_translate(
    localtest:   File "/usr/lib/python3.8/site-packages/py_mmd_tools/xml_utils.py", line 89, in xml_translate
    localtest:     xml_doc = ET.ElementTree(file=xml_file)
    localtest:   File "src/lxml/etree.pyx", line 3153, in lxml.etree.ElementTree
    localtest:   File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
    localtest:   File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
    localtest:   File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
    localtest:   File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
    localtest:   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
    localtest:   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
    localtest:   File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
    localtest:   File "/mmddir/metopb-avhrr-20201201155244-20201201160031.xml", line 140
    localtest: lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: metadata_identifier line 2 and mmd, line 140, column 11
    localtest: 
    localtest: During handling of the above exception, another exception occurred:
    localtest: 
    localtest: Traceback (most recent call last):
    localtest:   File "/usr/local/bin/xmlconverter.py", line 150, in <module>
    localtest:     main(
    localtest:   File "/usr/local/bin/xmlconverter.py", line 77, in main
    localtest:     print(f"failed on: {i} - {e.message}")
    localtest: AttributeError: 'XMLSyntaxError' object has no attribute 'message'
    localtest: Done
    localtest: /usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3185: SAWarning: Did not recognize type 'geometry' of column 'wkb_geometry'
    localtest:   util.warn(
    localtest: /usr/local/lib/python3.8/site-packages/owslib/iso.py:116: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
    localtest:   warnings.warn(
    localtest: /usr/local/lib/python3.8/site-packages/owslib/iso.py:543: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
    localtest:   warnings.warn(
    localtest: ./deploy-metadata.sh: line 41: /bin/rm: Argument list too long
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Not sure, but I think there are two problems here. First xml converter. Second there are too many files in one directory.

I think the last one might be solved by the new setup, but I'm not sure.

**Comment by TAlonglong** [comment]
First one was a typo in a xml file introduced after manual editing a generated xml file for testing. Fixed

**Comment by aheimsbakk** [comment]
Repo will be archived. Closing issue.
